name: "\U0001F41E New Bug Report"
description: Found a bug? Here you can send us a detailed report. We will be happy to look into it for you.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to report this bug! In order to be able to help you soundly we are dependent on your cooperation. Please provide us all the information you have as detailed as possible. It will save you and us time and improve the chance to fix the bug for all of us quickly!
  - type: checkboxes
    id: checkboxes
    attributes:
      label: First things first 🤗
      description: "Before submitting a bug here, please make sure you do the following:"
      options:
        - label: Make sure that you did read the [docs for server-side setup](https://inertiajs.com/server-side-setup).
          required: true
        - label: Make sure that there isn't [an open issue](https://github.com/inertiajs/inertia-laravel/issues) reporting the same bug.
          required: true
        - label: Make sure this is a server-side bug in the adapter and not a Javascript bug. Please report Javascript bugs [here](https://github.com/inertiajs/inertia/issues).
          required: true
        - label: Make sure that this is really a bug. Please use [GitHub Discussion](https://github.com/inertiajs/inertia/discussions/new?category=help) or our [Discord Server](https://discord.gg/inertiajs) for questions and discussions.
          required: true
        - label: Make sure the provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Please provide us a clear and concise description of the bug. If you intend to submit a PR for this issue, please let us know as well. Thank you!
      placeholder: Bug description
    validations:
      required: true
  - type: input
    id: reproduction-link
    attributes:
      label: Link to reproduction
      description: Ideally, please provide a link to a repo that can be used to reproduce the problem you are having. If a report is vague (e.g. just a general error message) and we have no way to easily reproduce the error, it is likely that fixing the error will take much longer.
      placeholder: https://github.com/yourGitHub/minimal-reproduction-repo
    validations:
      required: false
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide us a step by step description of how we can reproduce the bug.
      placeholder: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: version-info
    attributes:
      label: Versions
      description: |
        Please specify the versions  for:
        - `laravel/framework` version: #.#.#
        - `inertiajs/inertia-laravel` version: #.#.#
        - `PHP` version: #.#.#
      placeholder: Copy the above block and provide the used version for each
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Feel free to provide additional relevant information and context (e.g. data dumps, screen shots).
