blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions on GitHub
    url: https://github.com/inertiajs/inertia-laravel/discussions
    about: Want the good ol' board style? Talk with like-minded people and ask questions about Inertia.js here on GitHub.
  - name: Questions & Discussions on Discord
    url: https://discord.gg/inertiajs
    about: Want it in real time? Talk with like-minded people and ask questions about Inertia.js on our Discord server.
  - name: Want to support our work? ❤️
    url: https://github.com/sponsors/reinink
    about: We spend a lot of time on Inertia.js! In order to continue to provide you with a great developer experience and to constantly improve Inertia.js, we rely on your support. Please consider to sponsor us! ❤️ Sponsorship money goes to @reinink. However, we are sharing and working on a direct Inertia sponsorship .
